# Generated by Django 4.2.4 on 2023-08-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postvote',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='postvote',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='user_post_vote'),
        ),
    ]
