# Generated by Django 4.2.4 on 2023-08-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_alter_post_comments_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("deleted", "Deleted"),
                ],
                default="draft",
                max_length=9,
            ),
        ),
    ]
