# Generated by Django 4.2.4 on 2023-08-19 03:32

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_post_uuid"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="commentvote",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="commentvote",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="commentvote",
            name="user",
        ),
        migrations.AlterField(
            model_name="post",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="CommentVote",
        ),
    ]
