# Generated by Django 4.2.4 on 2023-08-28 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0007_alter_commentvote_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="publish_at",
            new_name="published_at",
        ),
    ]
