# Generated by Django 4.2.4 on 2023-08-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpublic",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
