# Generated by Django 4.2.4 on 2023-08-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_userpublic_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpublic",
            name="comments_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userpublic",
            name="votes_down_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userpublic",
            name="votes_up_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
