# Generated by Django 4.2.4 on 2023-08-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_userpublic_comments_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpublic",
            name="external_user_uid",
            field=models.CharField(db_index=True, max_length=36, unique=True),
        ),
    ]
