# Generated by Django 4.2.4 on 2023-08-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_userpublic_external_user_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpublic",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
