# Generated by Django 4.2.4 on 2023-08-16 09:08

from django.db import migrations, models

import common.deconstructibles


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_userpublic_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userpublic",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="userpublic",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=common.deconstructibles.upload_to(
                    "users/avatars/%Y/%m/%d", "external_user_uid"
                ),
            ),
        ),
    ]
