# Generated by Django 4.2.4 on 2023-08-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_userpublic_options_alter_userpublic_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpublic",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
