version: "3"

services:
  kapibara-monolith:
    restart: unless-stopped
    build: .
    env_file:
      - .env
    volumes:
      - .:/app/src
    ports:
      - "8888:8000"
    depends_on:
      - kapibara-db

  kapibara-db:
    image: postgres:15.3
    restart: unless-stopped
    ports:
      - "54321:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  db-data:
