[tool.black]
line-length = 90
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
/(
    \.idea
  | \.git
  | \.pytest_cache
  | \.venv
)/
'''

[tool.isort]
line_length = 90
profile = "black"
multi_line_output = 3
balanced_wrapping = true
include_trailing_comma = true
use_parentheses = true

[tool.pytest.ini_options]
addopts = "--reuse-db --nomigrations --show-capture=no --disable-socket -vv"
filterwarnings = "ignore::DeprecationWarning"
timeout = 300
DJANGO_SETTINGS_MODULE = "core_app.settings"
