# Generated by Django 4.2.4 on 2023-08-28 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="commentvote",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="commentvote",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="comments.comment",
            ),
        ),
        migrations.AlterField(
            model_name="commentvote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_votes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="commentvote",
            name="value",
            field=models.SmallIntegerField(choices=[(1, "Upvote"), (-1, "Downvote")]),
        ),
        migrations.AddConstraint(
            model_name="commentvote",
            constraint=models.UniqueConstraint(
                fields=("user", "comment"), name="user_comment_vote"
            ),
        ),
    ]
